DeOtters/INF1920-ELBHO-Android-App

.idea/.name
app/src/main/java/nl/otters/elbho/activities/LoginActivity.kt
app/src/main/java/nl/otters/elbho/activities/NavigationActivity.kt
app/src/main/res/layout/activity_navigation.xml
app/src/main/res/values/styles.xml

Uitloggen functionliteit

---

app/src/main/java/nl/otters/elbho/activities/NavigationActivity.kt

Nu sluit de terugknop netjes de navigatie en volgt hij de nav_graph.

Back button behaviour

---

app/src/main/AndroidManifest.xml
app/src/main/java/nl/otters/elbho/utils/ZoomOutPageTransformer.kt
app/src/main/java/nl/otters/elbho/views/activities/LoginActivity.kt
app/src/main/java/nl/otters/elbho/views/activities/NavigationActivity.kt
app/src/main/java/nl/otters/elbho/views/fragments/AvailabilityFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/CreateInvoiceFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/InvoiceFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/OverviewFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_navigation.xml
app/src/main/res/layout/fragment_create_invoice.xml
app/src/main/res/values/strings.xml

Fixed login button not visible when keyboard is up
Login button is now disabled when logging in
Added a nice transition to the tab view
Changed some placeholder naming
Spinner is now shown when data is loaded from API
File upload beginnetje

Misc fixes

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/models/Vehicle.kt
app/src/main/java/nl/otters/elbho/repositories/AdviserRepository.kt
app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/services/VehicleService.kt
app/src/main/java/nl/otters/elbho/utils/DateParser.kt
app/src/main/java/nl/otters/elbho/viewModels/VehicleViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/drawable/calendar_border.xml
app/src/main/res/layout/fragment_vehicle.xml
app/src/main/res/layout/fragment_vehicle_reservation.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Overall good progress
Added some TODO actions for after the BETA and need to add some more

Vehicle reservation works

---

.idea/codeStyles/Project.xml
app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/adapters/VehicleListAdapter.kt
app/src/main/java/nl/otters/elbho/models/Vehicle.kt
app/src/main/java/nl/otters/elbho/repositories/AdviserRepository.kt
app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/services/VehicleService.kt
app/src/main/java/nl/otters/elbho/viewModels/VehicleViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt

Alles doet het weer zoals bij de oude API alleen nog DELETE CALL fixen.

Vehicle fixes

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/adapters/VehicleReservedListAdapter.kt
app/src/main/java/nl/otters/elbho/models/Vehicle.kt
app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/services/VehicleService.kt
app/src/main/java/nl/otters/elbho/viewModels/VehicleViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/res/layout/component_vehicle_reserved_listitem.xml
app/src/main/res/layout/fragment_vehicle_reservation.xml
app/src/main/res/values/strings.xml

- reserved tijden worden getoond tijdens reserveren
- kleine annpassingen en fixes
TODO:
- Google API voor maps

Vehicle zo goed als klaar

---

app/src/main/AndroidManifest.xml
app/src/main/java/nl/otters/elbho/views/fragments/OpenRequestsFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/layout/fragment_vehicle_reserved.xml
app/src/main/res/values/strings.xml

Google maps implementatie werkt.

Elbho gmail account aangemaakt voor Google maps API implementatie.

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/adapters/VehicleListAdapter.kt
app/src/main/java/nl/otters/elbho/adapters/VehicleReservedListAdapter.kt
app/src/main/java/nl/otters/elbho/models/Vehicle.kt
app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/services/VehicleService.kt
app/src/main/java/nl/otters/elbho/viewModels/VehicleViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/values/strings.xml

Alles in orde, behalve error handling.

Vehicle reservation functies werken.

---

app/src/main/java/nl/otters/elbho/models/Vehicle.kt
app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/services/VehicleService.kt
app/src/main/java/nl/otters/elbho/utils/DateParser.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt

Verder kleine foutjes eruit gehaald.

vehicle API call aangepast na laatste aanpassing van Bas.

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/res/layout/fragment_vehicle_reservation.xml

- reservation cars pas weergeven als begin en eind tijd zijn ingevoerd

Laatste vehicle changes doorgevoerd:

---

app/src/main/java/nl/otters/elbho/utils/DateParser.kt
app/src/main/java/nl/otters/elbho/views/fragments/CopyWeekFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/CreateAvailabilityFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/RequestFragment.kt
app/src/main/res/layout/component_availability_input.xml
app/src/main/res/layout/component_copy_week.xml
app/src/main/res/layout/fragment_copy_week.xml
app/src/main/res/layout/fragment_create_availability.xml
app/src/main/res/layout/fragment_request.xml
app/src/main/res/values/strings.xml

Datum en tijd samenvoegen
Datumblokje moet ook het jaar bevatten
Titel ook beschikbaarheid
Van en tot 1x en alleen bovenaan
De invulblokjes leeg en niet --:--
Iets compacter nieuw beschikbaarheid scherm (zoals ios)
Oranje checkboxes
Titel veranderen naar beschikbaarheid
2 maanden in de toekomst week kopieren (8 weken)

feat: small fixes

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/layout/fragment_vehicle.xml
app/src/main/res/layout/fragment_vehicle_reservation.xml
app/src/main/res/values/strings.xml

- toast has orange background color
- text if no reservations made
- etc.

Final changes vehicle reservation:

---

app/src/main/java/nl/otters/elbho/views/activities/NavigationActivity.kt
app/src/main/java/nl/otters/elbho/views/fragments/RequestFragment.kt
app/src/main/res/layout-sw600dp/activity_login.xml
app/src/main/res/layout-sw600dp/component_listitem.xml
app/src/main/res/layout-sw600dp/component_textdisplay.xml
app/src/main/res/layout-sw600dp/component_vehicle_listitem.xml
app/src/main/res/layout-sw600dp/fragment_availability.xml
app/src/main/res/layout-sw600dp/fragment_create_invoice.xml
app/src/main/res/layout-sw600dp/fragment_invoice.xml
app/src/main/res/layout-sw600dp/fragment_invoice_listitem.xml
app/src/main/res/layout-sw600dp/fragment_overview.xml
app/src/main/res/layout-sw600dp/fragment_request.xml
app/src/main/res/layout-sw600dp/fragment_vehicle.xml
app/src/main/res/layout-sw600dp/fragment_vehicle_reservation.xml
app/src/main/res/layout-sw600dp/fragment_vehicle_reserved.xml
app/src/main/res/values-sw600dp/screen.xml
app/src/main/res/values/screen.xml

- login view
- overview view
- request views
(nog geen navigationmenu, need help!)

Begin tabletversie:

---

app/src/main/java/nl/otters/elbho/utils/VehicleLocationProvider.kt
app/src/main/java/nl/otters/elbho/views/activities/NavigationActivity.kt
app/src/main/java/nl/otters/elbho/views/fragments/RequestFragment.kt
app/src/main/res/values/strings.xml

Side menu fixed for real

---

app/src/main/java/nl/otters/elbho/models/Location.kt
app/src/main/java/nl/otters/elbho/repositories/LocationRepository.kt
app/src/main/java/nl/otters/elbho/services/LocationService.kt
app/src/main/java/nl/otters/elbho/utils/VehicleLocationProvider.kt
app/src/main/java/nl/otters/elbho/viewModels/RequestViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/RequestFragment.kt

Signed-off-by: juanalb <juan@zimmermanzimmerman.com>

feat: location

---

app/src/main/java/nl/otters/elbho/views/activities/NavigationActivity.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/res/layout-sw600dp/fragment_availability.xml
app/src/main/res/layout-sw600dp/fragment_copy_week.xml
app/src/main/res/layout-sw600dp/fragment_create_availability.xml
app/src/main/res/layout-sw600dp/fragment_invoice.xml
app/src/main/res/layout-sw600dp/fragment_invoice_listitem.xml
app/src/main/res/layout-sw600dp/fragment_overview.xml
app/src/main/res/layout-sw600dp/fragment_request.xml
app/src/main/res/layout-sw600dp/fragment_vehicle.xml
app/src/main/res/layout-sw600dp/fragment_vehicle_reservation.xml
app/src/main/res/layout-sw600dp/fragment_vehicle_reserved.xml
app/src/main/res/values/strings.xml

- navigationcontroller werkt! (geen crashes)
- alle views niet meer gesplitst
- verder kleine aanpassingen waar nodig.

Tablet beta version 1:

---

app/src/main/java/nl/otters/elbho/views/activities/LoginActivity.kt
app/src/main/java/nl/otters/elbho/views/activities/NavigationActivity.kt
app/src/main/java/nl/otters/elbho/views/fragments/OverviewFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt

Login button works for API level 21 
Added check in navigation activity if the user is logged in.
Removed all user logged in checks in fragments, since navigation activity is parent.

API 21 - Login button

---

app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/utils/DateParser.kt
app/src/main/java/nl/otters/elbho/viewModels/VehicleViewModel.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/values/strings.xml

- fixed hacky code
- some other refactor stuff

Vehicle code refactor and errorhandling

---

app/src/main/java/nl/otters/elbho/adapters/VehicleCarListAdapter.kt
app/src/main/java/nl/otters/elbho/utils/DateParser.kt
app/src/main/java/nl/otters/elbho/views/fragments/AvailabilityFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/CreateAvailabilityFragment.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt
app/src/main/res/layout-sw600dp/component_listitem.xml
app/src/main/res/layout/component_listitem.xml

- selecteren auto reservering tijd nu onafhankelijk van elkaar
- bij selecteren tijd availability, datum nu met dashes ipv slashes
- items in afspraken recyclerview, als te lang worden deze afgekapt...
- availability, haalt nu afspraken van huidige dag tot in de toekomst (niet meer begin van de maand, was namelijk niet meer nodig, toch?)
- availability, bij selecteren tijden van beschikbaarheid niet meer + 2 uur maar plus 1 minuut. (moet nog steeds anders tho)

AEen paar algemene aanpassingen die nodig waren:

---

app/src/main/java/nl/otters/elbho/repositories/VehicleRepository.kt
app/src/main/java/nl/otters/elbho/utils/ResponseHandler.kt
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt

- kijk even hoe ik deze implementeer in de vehicle fragment
- kijk ook even hoe ik deze implementeer in de vehiclerepository

Aresponse handler toegevoegd in utils

---

app/src/main/AndroidManifest.xml
app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservedFragment.kt
app/src/main/res/values/secrets.xml
app/src/main/res/values/strings.xml

- en errorhandling toegepast als google map locatie in reserverd vehicle
detail view niet kan worden weergegeven..

AResourcefile aangemaakt voor api key

---

app/src/main/java/nl/otters/elbho/views/fragments/VehicleReservationFragment.kt

- mindate aangepast anders chrash

hotfix voor api21 vehicle reservation
